from mlir.ir import Context, Location, Diagnostic, Module
from mlir.ir import MLIRError
from mlir.passmanager import PassManager
import mlir.dialects.gpu as gpu
import mlir.dialects.gpu.passes
from mlir.ir import Context

def dump_diag(diag):
    # diag.severity is an enum; diag.location and diag.message are strings
    print(f"[{diag.severity.name}] {diag.location}: {diag.message}")
    for n in diag.notes:
        print(f"  note: {n.location}: {n.message}")
    # Returning None is fine; the handler still counts as “handled”.


def run(f):
    with Context() as ctx, Location.unknown(ctx):
        ctx.enable_multithreading(False)
        ctx.emit_error_diagnostics = True
        ctx.attach_diagnostic_handler(dump_diag)
        try:
            f()
        except MLIRError as e:
            print(f"Exception: <{e}>")

            # CHECK: message: Unable to parse operation assembly
            print(f"message: {e.message}")

            # CHECK: error_diagnostics[0]:           loc("use") operand #0 does not dominate this use
            # CHECK: error_diagnostics[0].notes[0]:  loc("use") see current operation: "test.use"(%0) : (i64) -> ()
            # CHECK: error_diagnostics[0].notes[1]:  loc("def") operand defined here (op in the same block)
            print(
                "error_diagnostics[0]:          ",
                e.error_diagnostics[0].location,
                e.error_diagnostics[0].message,
            )
            print(
                "error_diagnostics[0].notes[0]: ",
                e.error_diagnostics[0].notes[0].location,
                e.error_diagnostics[0].notes[0].message,
            )
            print(
                "error_diagnostics[0].notes[1]: ",
                e.error_diagnostics[0].notes[1].location,
                e.error_diagnostics[0].notes[1].message,
            )


    return f


# CHECK-LABEL: testGPUToLLVMBin
@run
def testGPUToLLVMBin():
    module = Module.parse(
        r"""
module attributes {gpu.container_module} {
gpu.module @kernel_module1 [#nvvm.target<chip = "sm_70">] {
llvm.func @kernel(%arg0: i32, %arg1: !llvm.ptr,
    %arg2: !llvm.ptr, %arg3: i64, %arg4: i64,
    %arg5: i64) attributes {gpu.kernel} {
    llvm.return
}
}
}
"""
    )
    print(module)
    pm = PassManager("any")

    pm.add("gpu-module-to-binary{format=llvm}")
    # pm.enable_ir_printing(enable_debug_info=True)
    pm.run(module.operation)
    # # CHECK-LABEL: gpu.binary @kernel_module1
    # print(module)

    # o = gpu.ObjectAttr(module.body.operations[0].objects[0])
    # # CHECK: #gpu.object<#nvvm.target<chip = "sm_70">, offload = "{{.*}}">
    # print(o)
    # # CHECK: #nvvm.target<chip = "sm_70">
    # print(o.target)
    # # CHECK: offload
    # print(gpu.CompilationTarget(o.format))
    # # CHECK: b'{{.*}}'
    # print(o.object)
    # # CHECK: None
    # print(o.properties)
testGPUToLLVMBin()

# # CHECK-LABEL: testGPUToASMBin
# @run
# def testGPUToASMBin():
#     with Context():
#         module = Module.parse(
#             r"""
# module attributes {gpu.container_module} {
#   gpu.module @kernel_module2 [#nvvm.target<flags = {fast}>, #nvvm.target] {
#     llvm.func @kernel(%arg0: i32, %arg1: !llvm.ptr,
#         %arg2: !llvm.ptr, %arg3: i64, %arg4: i64,
#         %arg5: i64) attributes {gpu.kernel} {
#       llvm.return
#     }
#   }
# }
#     """
#         )
#     pm = PassManager("any")
#     pm.add("gpu-module-to-binary{format=isa}")
#     pm.run(module.operation)
#     # CHECK-LABEL:gpu.binary @kernel_module2
#     print(module)

#     o = gpu.ObjectAttr(module.body.operations[0].objects[0])
#     # CHECK: #gpu.object<#nvvm.target<flags = {fast}>
#     print(o)
#     # CHECK: #nvvm.target<flags = {fast}>
#     print(o.target)
#     # CHECK: assembly
#     print(gpu.CompilationTarget(o.format))
#     # CHECK: b'//\n// Generated by LLVM NVPTX Back-End{{.*}}'
#     print(o.object)
#     # CHECK: {LLVMIRToISATimeInMs = {{[0-9]+}} : i64, O = 2 : i32}
#     print(o.properties)
